### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by andyscott** [47deg/case-classy#12]
@jorgegalindocruces
I'm gearing up for an official release with PR #11. It would be really great to get a logo soon, since I writing some tutorials/documentation this weekend and I'd like to spin up a microsite.

**Comment by andyscott** [comment]
I drew some logos for inspiration:

Square
![case-classy-square](https://cloud.githubusercontent.com/assets/310363/21865684/6a86514e-d804-11e6-8a8a-a0ae9bf36b6e.png)
Wide

![case-classy-wide](https://cloud.githubusercontent.com/assets/310363/21865686/6c8f909a-d804-11e6-978b-6c6083581b62.png)

**Comment by Antoniojimenez47** [comment]
Hi! @andyscott 

I attach a design proposal to Case Classy.

This is a proposal, if you like, we choose this proposal and if you do not like it, we can work another design.

Cheers!
![caseclassy_brand-01](https://cloud.githubusercontent.com/assets/24649817/21889623/2cfc7990-d8ca-11e6-9c01-5f2efc138f5e.jpg)
![caseclassy_brand-02](https://cloud.githubusercontent.com/assets/24649817/21889624/2d2eab22-d8ca-11e6-87e0-2ec938b146fd.jpg)

**Comment by israelperezglez** [comment]
We could create a similar style for all our library logos. We can use a isometric perspective. Freestyle is a good example. @jorgegalindocruces what do you think about this?

**Comment by andyscott** [comment]
@Antoniojimenez47 I like the design you've put together. Is there some meaning to the shape/line because I'd really like for the logo to have some kind of meaning? Case classy is named after case classes/ADTs, so I was hoping to somehow incorporate ATDs into the design (which is why I added the `bottle + [martini | glass]` design).
@israelperezglez And yeah I'd really like to get an isometric design that's similar to the other logos we're doing.

**Comment by Antoniojimenez47** [comment]
Hi! @andyscott 
The design is a cocktail glass, I attach an image for you to see, and as for what @israelperezglez  said, I agree to make this logo in isometric.

Cheers!

![captura de pantalla 2017-01-13 a las 13 29 22](https://cloud.githubusercontent.com/assets/24649817/21930130/b20b2332-d994-11e6-8e76-c96a7c4ac1bb.png)

**Comment by andyscott** [comment]
Here are my thoughts:

I think some combination of A/B + C would make it more obvious that this is a cocktail glass.

A. Maybe make these regions the same color
B. Maybe make this region the same color
C. Maybe shorten the gap

Also, can we try a very dark blue color scheme? I really like blue 😄 


![feedback1](https://cloud.githubusercontent.com/assets/310363/21937886/3504fef8-d976-11e6-92e7-4ff5ada8d0c9.png)

**Comment by andyscott** [comment]
Yesterday I couldn't tell what the design is, and now I can't stop seeing the cocktail class. It's almost an optical illusion 😄.

**Comment by Antoniojimenez47** [comment]
Hi! @andyscott 

Attached the Case Classy logo, with the modifications you said.
I wait your answer.

@jorgegalindo has given his validation to send you.

Cheers!

![caseclassy_brand2-01](https://cloud.githubusercontent.com/assets/24649817/21983839/6903ad56-dbf3-11e6-9518-8b0e2599f717.jpg)

**Comment by jorgegalindocruces** [comment]
Cheers @andyscott ;-)

**Comment by Antoniojimenez47** [comment]
Hi! @andyscott 
I'm waiting for your validation by Github
Thankyou ;)

**Comment by jorgegalindocruces** [comment]
Hi guys, to moving forward this, we are going to approve the design and create all the assets related. 

Anyway, if we need have any change in the future we can do it!

**Comment by JorgeGalindo** [comment]
Hey there,

I'm afraid Andy brought one extra Jorge Galindo into the loop: me ; ) Don't
worry, it has happened before. But for what it's worth I do like that logo!

Jorge Galindo

2017-01-18 4:17 GMT-05:00 Jorge Galindo <notifications@github.com>:

**Comment by andyscott** [comment]
Thanks guys!
