### ISSUE TITLE
Assets microsite

### ISSUE THREAD

**Issue by anamariamv** [47deg/case-classy#28]
We need all assets for microsite design.

**Comment by Antoniojimenez47** [comment]
Hi! @andyscott 
I attach the .zip file with all the material for the microsite of Casse Classy, I also add the download link of the typography used:

https://fonts.google.com/specimen/Bitter

Cheers!
[assets_microsite_caseclassy.zip](https://github.com/47deg/case-classy/files/714415/assets_microsite_caseclassy.zip)

**Comment by andyscott** [comment]
Awesome, thanks!
