### ISSUE TITLE
Documentation Review

### ISSUE THREAD

**Issue by andyscott** [47deg/case-classy#33]
Hoping to get a review of the documentation, in particular everything included on the microsite. Feedback on language and technical content welcomed.

**Comment by raulraja** [comment]
@andyscott Do we have a PR for this?

**Comment by andyscott** [comment]
No, I wanted the overall result of all the PRs reviewed and I wasn't sure
how to do that other than just making an issue 😮.

**Comment by andyscott** [comment]
@raulraja / @MaureenElsberry I created #34 so you can add line by line comments

**Comment by raulraja** [comment]
PR reviewed, great docs!, let me know if you need anything else from me. Cheers!
